### ISSUE TITLE
dkim=pass unprotected

### ISSUE THREAD

**Issue by ztjuh** [trusteddomainproject/OpenDKIM#152]
What does the unprotected part in the header mean? Something to fix on my side?

`mail-tester.com; dkim=pass (2048-bit key; unprotected) ...`

**Comment by thegushi** [comment]
No dnssec.

-Dan

**Comment by ztjuh** [comment]
Ahh, my domain does have dnssec though... Is this from the receivers end or the senders end?

**Comment by thegushi** [comment]
Either.  If you have a dnssec-signed domainkey record, but the person validating your mail does not have a dnssec-aware resolver, they will see this.  If they have a dnssec-aware resolver, but you have not signed your zone, you will also see this.

It’s mostly harmless, but the problem it solves is:

“Wait, if we’re using cryptography to validate this stuff, shouldn’t we also have a secure channel to validate we’re not also getting spoofed keys?”

And the answer is “well, yes, but the complexity of the attack required to spoof DNS records just to send a forged email is…extreme”.

-Dan
(Who’s been dnssec-signing his zones since before the root was signed)

**Comment by ztjuh** [comment]
Okay, it's not that big of a issue as I understand, so I send a e-mail to gmail and it didn't show the unprotected, so it must be mail-tester.com which doesn't support dnssec.

Thank you for your explanation!
