### ISSUE TITLE
Real Opendkim Status?

### ISSUE THREAD

**Issue by olspanner** [trusteddomainproject/OpenDKIM#25]
Could one of the board or someone responsible at the TrustedDomainProject please clearly comment on the website where users can see & find it about the real status of OpenDKIMs many open bugs, at https://sourceforge.net/p/opendkim/bugs/?

Most recent is the OpenSSL 111 non-support on FreeBSD? Looks like for other OSs too.

There's been no response from the author for a very long time.

If the project's been abandoned that's cool. Can you just finally say so devs can stop spinning their wheels and figure out a different solution?

cc:
@mskucherawy 
@pmidge
@davecrocker
@AntiFreeze

**Comment by mskucherawy** [comment]
This was also sent to the lists.  My reply was as follows:

None of our open source projects have abandoned.  We have been operating at reduced capacity lately, however, which limits our ability to be as responsive as we have been in the past.

Still, a beta release for OpenDKIM was just tagged a couple of months ago, which fixes some bugs and adds support for ED25519 keys as described by the work of the DCRUP working group at the IETF:
https://github.com/trusteddomainproject/OpenDKIM/releases

...and most of our resources have been going into OpenARC lately, which is also working its way through the IETF process:
https://github.com/trusteddomainproject/OpenARC/releases

Moreover, we are in the process of moving most of our development work from SourceForge to github, as you can tell from the links above.  The code history for at least these two and OpenDMARC have been cloned, but there's no easy way to copy bug reports from the former to the latter.  Making matters worse, the mailing lists were offline some time ago due to the fact that they are being hosted by a volunteer whose servers had become unreachable, meaning we weren't able to post updates.  This appears, fortunately, to have now been rectified.

**Comment by pmidge** [comment]
You’re a good man, Kuch.

________________________________

**Comment by AliceWonderMiscreations** [comment]
Given that today is Thanksgiving - I really want to say Thank You. Just found the 2.11.0-beta2 today. Haven't tried building yet, not sure if it will build easily (I use LibreSSL - and on CentOS 7) but to see ED25519 support is on its way - THANK YOU.

Even if I spend hours and hours and still can't get it to build THANK YOU. I know eventually it will.

**Comment by mimi89999** [comment]
Hello,
Thank you for developing OpenDKIM. Do you plan to make a new stable release with ed25519 support soon? I would be happy to donate to help the project if that's an issue.

**Comment by Dmole** [comment]
With Issues and Pull requests piling up and no commits for 7 years, OpenDKIM appears abandoned.

There are 3 forks that have more than this projects 3,970 Commits:

```
Commits Fork
4,229 	/nickleverton/OpenDKIM
4,226 	/futatuki/OpenDKIM
4,096 	/oliv3r/OpenDKIM
```
and some progress elsewhere:

https://github.com/stalwartlabs/mail-auth

**Comment by futatuki** [comment]
@Dmole To see project status, we need to see develop branch instead of master.

> no commits for 7 years, 

3 years

> this projects 3,970 Commits

4097 commits

**Comment by Dmole** [comment]
Thanks @futatuki .

My point stands, but also past time to convert all the old branches with fewer commits than the default branch (master) to tags.
Doing so would make relevant branches more findable.

```
commits branch
4,097 	develop
4,091 	next
3,970 	master

3,880 	exp-kitterma-develop-2-9
3,880 	develop-2-9
3,783 	feature-msk-177
3,527 	feature-msk-sf3590860
2,939 	feature-msk-sf3518593
2,162 	feature-msk-sf3299041
2,123 	feature-msk-sf3060140
2,062 	bug-msk-sf3067338
2,061 	feature-msk-sf3171865
1,748 	feature-msk-sf2964396
1,676 	feature-msk-sf3137445
1,658 	feature-msk-sf3115073
1,529 	br-msk-solaris-cleanup
1,150 	br-msk-default-sender
  938 	br-msk-stats-redux
  581 	br-1-2
  420 	br-msk-doxygen

```

**Comment by Neustradamus** [comment]
I have not commented here in the past, but I have created several tickets:
- https://github.com/trusteddomainproject/OpenDKIM/issues/256
- https://github.com/trusteddomainproject/OpenDKIM/issues/255
- https://github.com/trusteddomainproject/OpenDMARC/issues/290
- https://github.com/trusteddomainproject/OpenDMARC/issues/291
- ...

@arekm has done a ticket here:
- https://github.com/trusteddomainproject/OpenDMARC/issues/294

A ghost user has done this ticket here:
- https://github.com/trusteddomainproject/OpenDKIM/issues/50
