### ISSUE TITLE
Can't build library in Centos 7 (1810)

### ISSUE THREAD

**Issue by oppocomputer** [trusteddomainproject/OpenDKIM#43]
I can't seem to build the OpenDKIM library in Centos 7 version 1810.
I will post screenshots later as I currently can't upload files.

**Comment by dilyanpalauzov** [comment]
You are more likely to get answer, if you tell what the problem is, without referencing any Linux distribution.

**Comment by lammertb** [comment]
There is no need to compile OpenDKIM on Centos 7, because it is available as a package in the EPEL repository released through the Fedora project. You can install it with the following commands:

yum install epel-release
yum install libopendkim libopendkim-devel opendkim

The first line will install the EPEL repository. The second line will install the OpenDKIM library, the development package (header files etc) and the OpenDKIM application.
