### ISSUE TITLE
Libbsd dependency on linux

### ISSUE THREAD

**Issue by TomasKorbar** [trusteddomainproject/OpenDKIM#53]
Hi,
On linux opendkim is dependent on libbsd because of strlcpy and strlcat functions. I found a way how to remove this dependency with simple wrapper which uses strncpy and strncat functions which are included in glibc. Would you be open to a change which would add configuration argument to configure.ac, some conditionals to makefiles and conditionals to source files which are using strl* functions?

**Comment by TomasKorbar** [comment]
Feel free to change pull request however you think is necessary:)

**Comment by martinbogo** [comment]
The dependency is there so that we don't have to maintain a separate implementation of these functions. Although we don't specifically target any distributions... the Trusted Domain Project does strive to maintain compatibility, maintainability, and security as much as possible.

The dependency on libbsd-dev is there as designed and will remain for now. If we need to change that in the future, this PR may help, but it will not be merged in.
