### ISSUE TITLE
v2.10.3 cannot verify the message signed by hotmail.com

### ISSUE THREAD

**Issue by sunhubs** [trusteddomainproject/OpenDKIM#96]
we leverage libopendkim to verify the DKIM signatures. originally we use v2.8.4, it seems to be ok except that somethimes there are body  hash mismatch issues, which is difficult to explain. And recently we upgrade to v2.10.3 because it seems to directly treat body hash mismatch as failure and seems to make sense when we check the messages. But after a while, we found that the v2.10.3 can not verify the message signed by hotmail.com.
**How we use the library:** 
we just put the whole message to the library, using dkim_chunk and dkim_eom to finish the verification.
**How to reproduce:**
directly use a hotmail account to send a message, this message will contain a signature with d=hotmail.com and s=selector1.

would you please have a check about this, if it is an issue, it is appreciate that you can fix it in future release. if it is the usage issue, it is appreciate that you can give some help.
Thanks

**Comment by dilyanpalauzov** [comment]
Use the code from the develop branch.

**Comment by sunhubs** [comment]
develop branch means it is in development, so when it will be released with the version tag, so that I can try that one

**Comment by dilyanpalauzov** [comment]
The last tagged release 2.10.3 was made on 12th May 2015. In October 2015 there was a fix, for a problem repeatedly reported since then: when after the colon between header name and header value, a new line follows immediately, opendkim does incorrect DKIM normalization.  Thank you for your patience.

In the mean time you can subscribe/send aggregate reports for your domains and interpret their content.

**Comment by G2CU** [comment]
tried the latest beta version, seems problem still existing

**Comment by sunhubs** [comment]
Good news, solution is found in https://sourceforge.net/p/opendkim/bugs/259/, can rebuild locally if nessary
